name: "Reusable2"

on:
  workflow_call:
    inputs:
      environment:
        type: string
      allow:
        default: true
        type: boolean
jobs:
  reusable_1:
    name: "Reusable1"
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}
    steps:
      - run: |
          echo Password is $PASSWORD
          if [[ $PASSWORD == *"hemligt"* ]]; then
            echo "This is the PROD password!"
          elif [[ $PASSWORD == *"test"* ]]; then
            echo "This is the TEST password!"
          else
            echo "No password provided"
          fi
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
