# This file is managed by Terraform in the https://github.com/atgse/github-config repository.
#
# Do NOT change content of the file in the repository as it will be overwritten!


name: "Release workflow"

on:
  workflow_dispatch:

jobs:
  workflow:
    runs-on: ubuntu-22.04
    steps:
      - name: Get Current Job Log URL
        uses: Tiryoh/gha-jobid-action@v0
        id: jobs
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          job_name: ${{ github.job }}

      - name: Output Current Job Log URL
        run: |
          echo ${{ steps.jobs.outputs.html_url }}
          curl -L ${{ steps.jobs.outputs.html_url }}