# This file is managed by Terraform in the https://github.com/atgse/github-config repository.
#
# Do NOT change content of the file in the repository as it will be overwritten!


name: "Release workflow"

on:
  workflow_dispatch:

jobs:
  workflow:
    runs-on: ubuntu-22.04
    outputs:
      job_id: ${{ steps.jobs.outputs.job_id }}
    steps:
      - name: Get Current Job Log URL
        id: jobs
        run: |
          JOBID=$(gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/atgse/andreas-poc/actions/runs/${{github.run_id}}/jobs | jq -cr '.jobs[].id')
          echo "job_id=$JOBID" >> "$GITHUB_OUTPUT"
        with:
          GH_TOKEN: ${{ github.token }}

  get_logs:
    runs-on: ubuntu-22.04
    needs: [workflow]
    steps:
      - name: Output Current Job Log URL
        run: |
          sleep 5
          echo ${{ needs.workflow.outputs.job_id }}
          gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${GITHUB_REPOSITORY}/actions/jobs/${{ needs.workflow.outputs.job_id }}/logs | grep "Current runner version"
        env:
          GH_TOKEN: ${{ github.token }}